urlshortener/shortenersite/urls.py
from django.conf.urls import include, url 
#from shortenersite.views import Shorten_url, Redirect_original, Index
import shortenersite.views
 
urlpatterns = [
    
    #url(r'^makeshort/(?P<pk>\d+)', Shorten_url.as_view(), name='shortenurl'),
    url(r'^makeshort/', shortenersite.views.shorten_url, name='shortenurl'),
    # this will create a URL's short id and return the short URL
    
    #url(r'^(?P&lt;short_id&gt;\w{6})', shortenersite.views.redirect_original, name='redirectoriginal'),
    #url(r'^(?P<short_id>\w{6})', Redirect_original.as_view(), name='redirectoriginal'),
    url(r'^(?P<short_id>\w{6})', shortenersite.views.redirect_original, name='redirectoriginal'),
    # when short URL is requested it redirects to original URL
    
    #url(r'^', Index.as_view(), name='index'),
    url(r'^', shortenersite.views.index, name='index'),
    # for our home/index page
    ]

urlshortener/urlshortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import shortenersite.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # if the URL pattern match /admin/ then open up admin panel
 
    url(r'', include('shortenersite.urls',namespace='shortenersite')),
    # if anything rather then /admin/ then it will look for shortenersite/urls
    ]

urlshortener/shortenersite/models.py
from django.db import models
from django.core.urlresolvers import reverse
from .basechanger import decimal2base_n, base_n2decimal

# Create your models here.
class Urls(models.Model):
    short_id = models.SlugField(max_length=6,primary_key=True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)
 
    def __str__(self):
        return self.httpurl

class Link (models.Model):
    url = models.URLField()

    def encurtar(link):
        l, _ = Link.objects.get_or_create(url=link.url)
        return str(decimal2base_n(l.pk))

    def expandir(slug):
        link_id = int(base_n2decimal(slug))
        l = Link.objects.get(pk=link_id)
        return l.url

    def get_absolute_url(self):
        return reverse("shortenurl", kwargs={"pk": self.pk})

    def url_curta(self):
        return reverse("redirectoriginal", kwargs={"short_id": Link.encurtar(self)})

urlshortener/shortenersite/views.py
#from django.shortcuts import render

# Create your views here.

from django.shortcuts import render_to_response, get_object_or_404, redirect
import random, string, json
from shortenersite.models import Urls
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.core.context_processors import csrf
#from django.core.urlresolvers import reverse
#from django.views.generic.edit import CreateView
#from django.views.generic import DetailView
#from django.views.generic.base import RedirectView
#from .models import Link
 
def index(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('shortenersite/index.html', c)
 
#class Index(CreateView):
#    model = Link
#    fields = ["url"]

#    def form_valid (self, form):
#        prev = Link.objects.filter(url=form.instance.url)
#        if prev:
#            return redirect ("shorten_url", pk=prev[0].pk)
#        return super(Index, self).form_valid(form)

def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id) # get object, if not        found return 404 error
    url.count += 1
    url.save()
    return HttpResponseRedirect(url.httpurl)

#class Redirect_original(RedirectView):
#     permanent = False
     
#     def get_redirect_url(self, *args, **kwargs):
#         return Link.expandir(kwargs["short_id"])
 
def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        short_id = get_short_code()
        b = Urls(httpurl=url, short_id=short_id)
        b.save()
 
        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + short_id
        return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")
 
#class Shorten_url(DetailView):
#     model = Link

def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Urls.objects.get(pk=short_id)
        except:
            return short_id

urlshortener/shortenersite/templates/shortenersite/base.html
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}Welcome to mysite{% endblock %}</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" type="text/css" href="{% static 'shortenersite/css/custom.css' %}" />
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script type="text/javascript">
 $(function() {
 $('#submitButton').click(function() {
 $.ajax({
 type: "POST",
 url: "/makeshort/",
 data: {
 'url' : $('#url').val(),
 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
 },
 success: returnSuccess,
 dataType: 'json'
 });
 });
});
  
function returnSuccess(data, textStatus, jqXHR) {
 if(data.url) {
 $('#url-result').text(data.url);
 $('#url').val("");
 } else {
 $('#url-result').text("Do not submit blank."); 
 }
   
}
</script>
<body>
<div id="wrap">
<header>
 <h1><a href="{% url 'shortenersite:index' %}">URL Shortner</a><small>Shorten the URL</small></h1>
</header>
  
<div id="content">
{% block content %}
  
{% endblock %}
</div>
</div>
</body>
</html>

urlshortener/shortenersite/templates/shortenersite/index.html
<!DOCTYPE html>
<html>
{% extends "shortenersite/base.html" %}
<head>
 <title>{% block title %}URL Shortner - Make your URL shorter!{% endblock %}</title>
</head>

<body>
  
<div id="content">
{% block content %}

<div class="panel panel-default">
 
 <div class="panel-body">
 
  <div class="col-sm-9">
  <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.facebook.com" />
  </div>
 
  <div class="col-sm-3">
  {% csrf_token %}
  <button id="submitButton" class="btn btn-primary">Submit</button></p>
  </div>
 
 </div>
 <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>

</div>
{% endblock %}
</div>
</body>
</html>

urlshortener/shortenersite/templates/shortenersite/link_form.html
<!DOCTYPE html>
<html>
{% extends "shortenersite/base.html" %}
<head>
 <title>{% block title %}URL Shortner - Make your URL shorter!{% endblock %}</title>
</head>

<body>
  
<div id="content">
{% block content %}

<div class="panel panel-default">
 
 <div class="panel-body">
 
  <div class="col-sm-9">
  <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.facebook.com" />
  </div>
 
  <div class="col-sm-3">
  {% csrf_token %}
  <button id="submitButton" class="btn btn-primary">Submit</button></p>
  </div>
 
 </div>
 <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>

</div>
{% endblock %}
</div>
</body>
</html>